services:
  - type: web
    name: jfeid-web
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: RENDER_DUMMY
        value: "true"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: APP_URL
        sync: false
      - key: ASSET_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
    disk:
      name: storage
      mountPath: /var/www/storage
      sizeGB: 1
